openapi: 3.0.3
info:
  title: manual
  version: 0.0.1
  description: |
    manual-api

paths:
  /manual-urls:
    post:
      tags:
        - マニュアル
      summary: マニュアルDL用URL作成
      description: ログインユーザーが所属しているテナントに紐づく利用者マニュアルをダウンロードするためのURLを作成します
      security:
        - Tenant/AdvisoryChannel/Branch/Fa: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: 'manual'
      responses:
        '201':
          description: URL作成成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - manual_url
                properties:
                  manual_url:
                    type: string
                    description: マニュアルをダウンロードするためのURL
                    example: 'https://awsexamplebucket.s3.amazonaws.com/test2.txt?AWSAccessKeyId=AKIAEXAMPLEACCESSKEY&Signature=EXHCcBe%EXAMPLEKnz3r8O0AgEXAMPLE&Expires=1555531131'
        '403':
          $ref: '../afs-client.yaml#/components/responses/ForbiddenResponse'
        '500':
          $ref: '../afs-client.yaml#/components/responses/InternalServerErrorResponse'
