openapi: 3.0.3
info:
  title: merged-pdf
  version: 0.0.1
  description: |
    merged-pdf-api

paths:
  /merged-pdf-url:
    post:
      tags:
        - ゴールプランの提案書に合成するPDF
      summary: ゴールプランの提案書に合成するPDFをダウンロード用URL作成
      description: ログインユーザーが所属しているテナントに紐づくゴールプランの提案書に合成するPDFをダウンロードするためのURLを作成する
      security:
        - Bearer: []

      responses:
        '201':
          description: URL作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  introduction:
                    type: string
                    description: 案内PDFをダウンロードするためのURL
                    example: 'https://awsexamplebucket.s3.amazonaws.com/introduction.pdf?AWSAccessKeyId=AKIAEXAMPLEACCESSKEY&Signature=EXHCcBe%EXAMPLEKnz3r8O0AgEXAMPLE&Expires=1555531131'
                  operation:
                    type: string
                    description: 運用PDFをダウンロードするためのURL
                    example: 'https://awsexamplebucket.s3.amazonaws.com/operation.pdf?AWSAccessKeyId=AKIAEXAMPLEACCESSKEY&Signature=EXHCcBe%EXAMPLEKnz3r8O0AgEXAMPLE&Expires=1555531131'
        '403':
          $ref: '../afs-client.yaml#/components/responses/ForbiddenResponse'
        '500':
          $ref: '../afs-client.yaml#/components/responses/InternalServerErrorResponse'
